
  (defun c:eee( / sh s ss ww ssn)
    (princ "粗")
    (setq sh (getvar "peditaccept"))
    (setvar "peditaccept" 0)
    (setvar "cmdecho" 0)
    (if (= jcxw_0 Nil) (setq jcxw_0 1))
    (setq ww (getdist (strcat "\n 请输入线宽 <" (rtos jcxw_0 2) ">: ")))
    (if (= ww nil) (setq ww jcxw_0))(setq jcxw_0 ww)
    (setq ss (ssget '((-4 . "<or")(0 . "LINE")(0 . "CIRCLE")(0 . "ARC")
                         (0 . "POLYLINE")(0 . "LWPOLYLINE")(-4 . "or>"))))
    (setq s 0) (command "undo" "be")
    (repeat (if ss (sslength ss) (progn (princ "\n 未选择对象。") 0))
       (setq ssn (ssname ss s) entyp (cdr (assoc 0 (entget ssn))))
       (cond ((= entyp "CIRCLE") (progn
           (setq rr (cdr (assoc 40 (entget ssn)))
                cen (cdr (assoc 10 (entget ssn))))
           (command "donut" (* 2 (- rr (/ ww 2))) (* 2 (+ rr (/ ww 2))) cen "")
           (command "erase" ssn "")))
           ((= entyp "LINE") (command "pedit" ssn "y" "w" ww ""))
    ((= entyp "ARC") (command "pedit" ssn "y" "w" ww ""))
           ((= entyp "LWPOLYLINE") (command "pedit" ssn "w" ww ""))
    ((= entyp "POLYLINE") (command "pedit" ssn "w" ww ""))
       )(setq s (1+ s))
     )(command "undo" "e")
     (setvar "peditaccept" sh)
    (princ)
)
 
